### PR TITLE
Fix errors when APP_b partition is not present

### PR DESCRIPTION
**Pull request by atharvanan1**
This fixes the script for setup without APP_b partition

### CODE REVIEW

**Comment by madisongh** [comment]
Thanks!

**Comment by atharvanan1** [comment]
Hey Matt,

Apparently, this commit breaks the gpt repartitioning in all images. It's because of this logic - https://github.com/madisongh/tegra-sysinstall/blob/1cb686973ed324449eb6d60de5fc4d05fbe34569/lib/tools-common.in#L557

I couldn't catch it, because my partitions were already resized. Further, I'm not sure what the purpose of that check is, when we are already checking here (this is called earlier in `tegra-sysinstall` script - https://github.com/madisongh/tegra-sysinstall/blob/1cb686973ed324449eb6d60de5fc4d05fbe34569/lib/tools-common.in#L507 

Before I do any changes, I'd like to know your opinion on that

**Comment by madisongh** [comment]
Hmm.  It might be OK to change that first conditional to be `"$INITIAL_SETUP" = "yes"` instead, but let me think about that.  The script may have other assumptions about having a dual rootfs partition setup, too, since that was part of the original design, so other problems may crop up.

That section of `initialize_devices()` evolved from a prior project where I *didn't* re-partition the eMMC, but instead had some extra partitions in the flash XML file that were present just to get the installer going. It might be better for me to just clean that up, since it's no longer needed.

**Comment by atharvanan1** [comment]
Hey Matt, I had a discussion with Dan. We are going to focus more on A/B partition scheme. So, it would be wise to not spend much time on this right now, unless someone else needs it.

Thanks for your help! Really appreciate the work!

**Pull request merged**
